### ISSUE TITLE
DaggerAppComponent error

### ISSUE THREAD

**Issue by nknr** [Lajesh/NYTimeArticleList#2]
DaggerAppComponent class not found. I have also modified class name **AppComponent** based on package and their method is not found. 

![dragger](https://user-images.githubusercontent.com/18142767/59764332-322e2200-92b9-11e9-9c3b-7c6c25cbe8a2.PNG)

**Comment by AnupriyaPR** [comment]
Did you try to rebuild the project? You have to go Build -> Rebuild project. Remember that these classes are generated at compile-time.

**Comment by naveedahmad99** [comment]
Just **clean** your project and **rebuild** it. this fixed issue for me. @nknr

**Comment by AnupriyaPR** [comment]
Just remove the `import`. then clean . and run the app.

**Comment by Lajesh** [comment]
Please update your android studio. Clean the project and build again. It should be fine.
